// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import dynamic from 'next/dynamic';

export const registry = {
  'building-forms-hook-form': {
    name: 'building-forms-hook-form',
    demo: dynamic(
      () => import('@/content/concepts/building-forms-hook-form.demo')
    ),
    file: 'content/concepts/building-forms-hook-form.demo.tsx',
  },
  'building-forms-zod': {
    name: 'building-forms-zod',
    demo: dynamic(
      () => import('@/content/concepts/building-forms-zod.demo')
    ),
    file: 'content/concepts/building-forms-zod.demo.tsx',
  },
  'concepts-layouts': {
    name: 'concepts-layouts',
    demo: dynamic(
      () => import('@/content/concepts/concepts-layouts.demo')
    ),
    file: 'content/concepts/concepts-layouts.demo.tsx',
  },
  'error-handling': {
    name: 'error-handling',
    demo: dynamic(
      () => import('@/content/concepts/error-handling.demo')
    ),
    file: 'content/concepts/error-handling.demo.tsx',
  },
  'layout-forms': {
    name: 'layout-forms',
    demo: dynamic(
      () => import('@/content/concepts/layout-forms.demo')
    ),
    file: 'content/concepts/layout-forms.demo.tsx',
  },
  'logical-interaction': {
    name: 'logical-interaction',
    demo: dynamic(
      () => import('@/content/concepts/logical-interaction.demo')
    ),
    file: 'content/concepts/logical-interaction.demo.tsx',
  },
  'bookings-form': {
    name: 'bookings-form',
    demo: dynamic(
      () => import('@/content/recipes/bookings-form.demo')
    ),
    file: 'content/recipes/bookings-form.demo.tsx',
  },
  'core-table-print': {
    name: 'core-table-print',
    demo: dynamic(
      () => import('@/content/recipes/core-table-print.demo')
    ),
    file: 'content/recipes/core-table-print.demo.tsx',
  },
  'organization-search': {
    name: 'organization-search',
    demo: dynamic(
      () => import('@/content/recipes/organization-search.demo')
    ),
    file: 'content/recipes/organization-search.demo.tsx',
  },
  'async': {
    name: 'async',
    demo: dynamic(
      () => import('@/content/hooks/useAsyncListData/async.demo')
    ),
    file: 'content/hooks/useAsyncListData/async.demo.tsx',
  },
  'useTheme': {
    name: 'useTheme',
    demo: dynamic(
      () => import('@/content/hooks/useTheme/useTheme.demo')
    ),
    file: 'content/hooks/useTheme/useTheme.demo.tsx',
  },
  'accordion-basic': {
    name: 'accordion-basic',
    demo: dynamic(
      () => import('@/content/components/collection/accordion/accordion-basic.demo')
    ),
    file: 'content/components/collection/accordion/accordion-basic.demo.tsx',
  },
  'basic-accordion': {
    name: 'basic-accordion',
    demo: dynamic(
      () => import('@/content/components/collection/accordion/basic-accordion.demo')
    ),
    file: 'content/components/collection/accordion/basic-accordion.demo.tsx',
  },
  'multi-select-accordion': {
    name: 'multi-select-accordion',
    demo: dynamic(
      () => import('@/content/components/collection/accordion/multi-select-accordion.demo')
    ),
    file: 'content/components/collection/accordion/multi-select-accordion.demo.tsx',
  },
  'single-select-accordion': {
    name: 'single-select-accordion',
    demo: dynamic(
      () => import('@/content/components/collection/accordion/single-select-accordion.demo')
    ),
    file: 'content/components/collection/accordion/single-select-accordion.demo.tsx',
  },
  'table-async': {
    name: 'table-async',
    demo: dynamic(
      () => import('@/content/components/collection/table/table-async.demo')
    ),
    file: 'content/components/collection/table/table-async.demo.tsx',
  },
  'table-column-width': {
    name: 'table-column-width',
    demo: dynamic(
      () => import('@/content/components/collection/table/table-column-width.demo')
    ),
    file: 'content/components/collection/table/table-column-width.demo.tsx',
  },
  'table-compact': {
    name: 'table-compact',
    demo: dynamic(
      () => import('@/content/components/collection/table/table-compact.demo')
    ),
    file: 'content/components/collection/table/table-compact.demo.tsx',
  },
  'table-disabled': {
    name: 'table-disabled',
    demo: dynamic(
      () => import('@/content/components/collection/table/table-disabled.demo')
    ),
    file: 'content/components/collection/table/table-disabled.demo.tsx',
  },
  'table-dynamic': {
    name: 'table-dynamic',
    demo: dynamic(
      () => import('@/content/components/collection/table/table-dynamic.demo')
    ),
    file: 'content/components/collection/table/table-dynamic.demo.tsx',
  },
  'table-multi-mode': {
    name: 'table-multi-mode',
    demo: dynamic(
      () => import('@/content/components/collection/table/table-multi-mode.demo')
    ),
    file: 'content/components/collection/table/table-multi-mode.demo.tsx',
  },
  'table-nested': {
    name: 'table-nested',
    demo: dynamic(
      () => import('@/content/components/collection/table/table-nested.demo')
    ),
    file: 'content/components/collection/table/table-nested.demo.tsx',
  },
  'table-single-mode': {
    name: 'table-single-mode',
    demo: dynamic(
      () => import('@/content/components/collection/table/table-single-mode.demo')
    ),
    file: 'content/components/collection/table/table-single-mode.demo.tsx',
  },
  'table-sorting': {
    name: 'table-sorting',
    demo: dynamic(
      () => import('@/content/components/collection/table/table-sorting.demo')
    ),
    file: 'content/components/collection/table/table-sorting.demo.tsx',
  },
  'badge-dark': {
    name: 'badge-dark',
    demo: dynamic(
      () => import('@/content/components/content/badge/badge-dark.demo')
    ),
    file: 'content/components/content/badge/badge-dark.demo.tsx',
  },
  'basic-badge': {
    name: 'basic-badge',
    demo: dynamic(
      () => import('@/content/components/content/badge/basic-badge.demo')
    ),
    file: 'content/components/content/badge/basic-badge.demo.tsx',
  },
  'icon-badge': {
    name: 'icon-badge',
    demo: dynamic(
      () => import('@/content/components/content/badge/icon-badge.demo')
    ),
    file: 'content/components/content/badge/icon-badge.demo.tsx',
  },
  'simple-body': {
    name: 'simple-body',
    demo: dynamic(
      () => import('@/content/components/content/body/simple-body.demo')
    ),
    file: 'content/components/content/body/simple-body.demo.tsx',
  },
  'card-form': {
    name: 'card-form',
    demo: dynamic(
      () => import('@/content/components/content/card/card-form.demo')
    ),
    file: 'content/components/content/card/card-form.demo.tsx',
  },
  'card-infos': {
    name: 'card-infos',
    demo: dynamic(
      () => import('@/content/components/content/card/card-infos.demo')
    ),
    file: 'content/components/content/card/card-infos.demo.tsx',
  },
  'divider-bold': {
    name: 'divider-bold',
    demo: dynamic(
      () => import('@/content/components/content/divider/divider-bold.demo')
    ),
    file: 'content/components/content/divider/divider-bold.demo.tsx',
  },
  'divider-section': {
    name: 'divider-section',
    demo: dynamic(
      () => import('@/content/components/content/divider/divider-section.demo')
    ),
    file: 'content/components/content/divider/divider-section.demo.tsx',
  },
  'divider-text': {
    name: 'divider-text',
    demo: dynamic(
      () => import('@/content/components/content/divider/divider-text.demo')
    ),
    file: 'content/components/content/divider/divider-text.demo.tsx',
  },
  'copyright-footer': {
    name: 'copyright-footer',
    demo: dynamic(
      () => import('@/content/components/content/footer/copyright-footer.demo')
    ),
    file: 'content/components/content/footer/copyright-footer.demo.tsx',
  },
  'list-footer': {
    name: 'list-footer',
    demo: dynamic(
      () => import('@/content/components/content/footer/list-footer.demo')
    ),
    file: 'content/components/content/footer/list-footer.demo.tsx',
  },
  'simple-header': {
    name: 'simple-header',
    demo: dynamic(
      () => import('@/content/components/content/header/simple-header.demo')
    ),
    file: 'content/components/content/header/simple-header.demo.tsx',
  },
  'headline': {
    name: 'headline',
    demo: dynamic(
      () => import('@/content/components/content/headline/headline.demo')
    ),
    file: 'content/components/content/headline/headline.demo.tsx',
  },
  'icon-fill': {
    name: 'icon-fill',
    demo: dynamic(
      () => import('@/content/components/content/icon/icon-fill.demo')
    ),
    file: 'content/components/content/icon/icon-fill.demo.tsx',
  },
  'icon-size': {
    name: 'icon-size',
    demo: dynamic(
      () => import('@/content/components/content/icon/icon-size.demo')
    ),
    file: 'content/components/content/icon/icon-size.demo.tsx',
  },
  'image-fit-position': {
    name: 'image-fit-position',
    demo: dynamic(
      () => import('@/content/components/content/image/image-fit-position.demo')
    ),
    file: 'content/components/content/image/image-fit-position.demo.tsx',
  },
  'image': {
    name: 'image',
    demo: dynamic(
      () => import('@/content/components/content/image/image.demo')
    ),
    file: 'content/components/content/image/image.demo.tsx',
  },
  'list-ordered': {
    name: 'list-ordered',
    demo: dynamic(
      () => import('@/content/components/content/list/list-ordered.demo')
    ),
    file: 'content/components/content/list/list-ordered.demo.tsx',
  },
  'list-unorded-stacked': {
    name: 'list-unorded-stacked',
    demo: dynamic(
      () => import('@/content/components/content/list/list-unorded-stacked.demo')
    ),
    file: 'content/components/content/list/list-unorded-stacked.demo.tsx',
  },
  'simple-list': {
    name: 'simple-list',
    demo: dynamic(
      () => import('@/content/components/content/list/simple-list.demo')
    ),
    file: 'content/components/content/list/simple-list.demo.tsx',
  },
  'svg': {
    name: 'svg',
    demo: dynamic(
      () => import('@/content/components/content/svg/svg.demo')
    ),
    file: 'content/components/content/svg/svg.demo.tsx',
  },
  'text-color': {
    name: 'text-color',
    demo: dynamic(
      () => import('@/content/components/content/text/text-color.demo')
    ),
    file: 'content/components/content/text/text-color.demo.tsx',
  },
  'text-default': {
    name: 'text-default',
    demo: dynamic(
      () => import('@/content/components/content/text/text-default.demo')
    ),
    file: 'content/components/content/text/text-default.demo.tsx',
  },
  'visually-hidden': {
    name: 'visually-hidden',
    demo: dynamic(
      () => import('@/content/components/content/visually-hidden/visually-hidden.demo')
    ),
    file: 'content/components/content/visually-hidden/visually-hidden.demo.tsx',
  },
  'XLoader-props': {
    name: 'XLoader-props',
    demo: dynamic(
      () => import('@/content/components/content/xloader/XLoader-props.demo')
    ),
    file: 'content/components/content/xloader/XLoader-props.demo.tsx',
  },
  'link-anchor': {
    name: 'link-anchor',
    demo: dynamic(
      () => import('@/content/components/content/link/link-anchor.demo')
    ),
    file: 'content/components/content/link/link-anchor.demo.tsx',
  },
  'link-disabled': {
    name: 'link-disabled',
    demo: dynamic(
      () => import('@/content/components/content/link/link-disabled.demo')
    ),
    file: 'content/components/content/link/link-disabled.demo.tsx',
  },
  'link-standard': {
    name: 'link-standard',
    demo: dynamic(
      () => import('@/content/components/content/link/link-standard.demo')
    ),
    file: 'content/components/content/link/link-standard.demo.tsx',
  },
  'link-target': {
    name: 'link-target',
    demo: dynamic(
      () => import('@/content/components/content/link/link-target.demo')
    ),
    file: 'content/components/content/link/link-target.demo.tsx',
  },
  'button-ghost': {
    name: 'button-ghost',
    demo: dynamic(
      () => import('@/content/components/form/button/button-ghost.demo')
    ),
    file: 'content/components/form/button/button-ghost.demo.tsx',
  },
  'button-icon': {
    name: 'button-icon',
    demo: dynamic(
      () => import('@/content/components/form/button/button-icon.demo')
    ),
    file: 'content/components/form/button/button-icon.demo.tsx',
  },
  'button-link': {
    name: 'button-link',
    demo: dynamic(
      () => import('@/content/components/form/button/button-link.demo')
    ),
    file: 'content/components/form/button/button-link.demo.tsx',
  },
  'button-primary': {
    name: 'button-primary',
    demo: dynamic(
      () => import('@/content/components/form/button/button-primary.demo')
    ),
    file: 'content/components/form/button/button-primary.demo.tsx',
  },
  'button-secondary': {
    name: 'button-secondary',
    demo: dynamic(
      () => import('@/content/components/form/button/button-secondary.demo')
    ),
    file: 'content/components/form/button/button-secondary.demo.tsx',
  },
  'button-size': {
    name: 'button-size',
    demo: dynamic(
      () => import('@/content/components/form/button/button-size.demo')
    ),
    file: 'content/components/form/button/button-size.demo.tsx',
  },
  'button-text': {
    name: 'button-text',
    demo: dynamic(
      () => import('@/content/components/form/button/button-text.demo')
    ),
    file: 'content/components/form/button/button-text.demo.tsx',
  },
  'basic-calendar': {
    name: 'basic-calendar',
    demo: dynamic(
      () => import('@/content/components/form/calendar/basic-calendar.demo')
    ),
    file: 'content/components/form/calendar/basic-calendar.demo.tsx',
  },
  'disabled-calendar': {
    name: 'disabled-calendar',
    demo: dynamic(
      () => import('@/content/components/form/calendar/disabled-calendar.demo')
    ),
    file: 'content/components/form/calendar/disabled-calendar.demo.tsx',
  },
  'range-calendar': {
    name: 'range-calendar',
    demo: dynamic(
      () => import('@/content/components/form/calendar/range-calendar.demo')
    ),
    file: 'content/components/form/calendar/range-calendar.demo.tsx',
  },
  'message-error': {
    name: 'message-error',
    demo: dynamic(
      () => import('@/content/components/content/message/message-error.demo')
    ),
    file: 'content/components/content/message/message-error.demo.tsx',
  },
  'message-info': {
    name: 'message-info',
    demo: dynamic(
      () => import('@/content/components/content/message/message-info.demo')
    ),
    file: 'content/components/content/message/message-info.demo.tsx',
  },
  'message-warn': {
    name: 'message-warn',
    demo: dynamic(
      () => import('@/content/components/content/message/message-warn.demo')
    ),
    file: 'content/components/content/message/message-warn.demo.tsx',
  },
  'autocomplete-async': {
    name: 'autocomplete-async',
    demo: dynamic(
      () => import('@/content/components/form/autocomplete/autocomplete-async.demo')
    ),
    file: 'content/components/form/autocomplete/autocomplete-async.demo.tsx',
  },
  'autocomplete-controlled': {
    name: 'autocomplete-controlled',
    demo: dynamic(
      () => import('@/content/components/form/autocomplete/autocomplete-controlled.demo')
    ),
    file: 'content/components/form/autocomplete/autocomplete-controlled.demo.tsx',
  },
  'autocomplete-uncontrolled': {
    name: 'autocomplete-uncontrolled',
    demo: dynamic(
      () => import('@/content/components/form/autocomplete/autocomplete-uncontrolled.demo')
    ),
    file: 'content/components/form/autocomplete/autocomplete-uncontrolled.demo.tsx',
  },
  'checkbox-disabled': {
    name: 'checkbox-disabled',
    demo: dynamic(
      () => import('@/content/components/form/checkbox/checkbox-disabled.demo')
    ),
    file: 'content/components/form/checkbox/checkbox-disabled.demo.tsx',
  },
  'checkbox-group': {
    name: 'checkbox-group',
    demo: dynamic(
      () => import('@/content/components/form/checkbox/checkbox-group.demo')
    ),
    file: 'content/components/form/checkbox/checkbox-group.demo.tsx',
  },
  'checkbox-indeterminate': {
    name: 'checkbox-indeterminate',
    demo: dynamic(
      () => import('@/content/components/form/checkbox/checkbox-indeterminate.demo')
    ),
    file: 'content/components/form/checkbox/checkbox-indeterminate.demo.tsx',
  },
  'date-field-basic': {
    name: 'date-field-basic',
    demo: dynamic(
      () => import('@/content/components/form/datefield/date-field-basic.demo')
    ),
    file: 'content/components/form/datefield/date-field-basic.demo.tsx',
  },
  'date-field-disabled': {
    name: 'date-field-disabled',
    demo: dynamic(
      () => import('@/content/components/form/datefield/date-field-disabled.demo')
    ),
    file: 'content/components/form/datefield/date-field-disabled.demo.tsx',
  },
  'date-field-error': {
    name: 'date-field-error',
    demo: dynamic(
      () => import('@/content/components/form/datefield/date-field-error.demo')
    ),
    file: 'content/components/form/datefield/date-field-error.demo.tsx',
  },
  'date-field-required': {
    name: 'date-field-required',
    demo: dynamic(
      () => import('@/content/components/form/datefield/date-field-required.demo')
    ),
    file: 'content/components/form/datefield/date-field-required.demo.tsx',
  },
  'combobox-async': {
    name: 'combobox-async',
    demo: dynamic(
      () => import('@/content/components/form/combobox/combobox-async.demo')
    ),
    file: 'content/components/form/combobox/combobox-async.demo.tsx',
  },
  'combobox-basic': {
    name: 'combobox-basic',
    demo: dynamic(
      () => import('@/content/components/form/combobox/combobox-basic.demo')
    ),
    file: 'content/components/form/combobox/combobox-basic.demo.tsx',
  },
  'combobox-controlled': {
    name: 'combobox-controlled',
    demo: dynamic(
      () => import('@/content/components/form/combobox/combobox-controlled.demo')
    ),
    file: 'content/components/form/combobox/combobox-controlled.demo.tsx',
  },
  'date-picker-basic': {
    name: 'date-picker-basic',
    demo: dynamic(
      () => import('@/content/components/form/datepicker/date-picker-basic.demo')
    ),
    file: 'content/components/form/datepicker/date-picker-basic.demo.tsx',
  },
  'date-picker-disabled': {
    name: 'date-picker-disabled',
    demo: dynamic(
      () => import('@/content/components/form/datepicker/date-picker-disabled.demo')
    ),
    file: 'content/components/form/datepicker/date-picker-disabled.demo.tsx',
  },
  'date-picker-error': {
    name: 'date-picker-error',
    demo: dynamic(
      () => import('@/content/components/form/datepicker/date-picker-error.demo')
    ),
    file: 'content/components/form/datepicker/date-picker-error.demo.tsx',
  },
  'date-picker-min-max': {
    name: 'date-picker-min-max',
    demo: dynamic(
      () => import('@/content/components/form/datepicker/date-picker-min-max.demo')
    ),
    file: 'content/components/form/datepicker/date-picker-min-max.demo.tsx',
  },
  'date-picker-required': {
    name: 'date-picker-required',
    demo: dynamic(
      () => import('@/content/components/form/datepicker/date-picker-required.demo')
    ),
    file: 'content/components/form/datepicker/date-picker-required.demo.tsx',
  },
  'number-field-amount': {
    name: 'number-field-amount',
    demo: dynamic(
      () => import('@/content/components/form/number-field/number-field-amount.demo')
    ),
    file: 'content/components/form/number-field/number-field-amount.demo.tsx',
  },
  'number-field-disabled': {
    name: 'number-field-disabled',
    demo: dynamic(
      () => import('@/content/components/form/number-field/number-field-disabled.demo')
    ),
    file: 'content/components/form/number-field/number-field-disabled.demo.tsx',
  },
  'number-field-error': {
    name: 'number-field-error',
    demo: dynamic(
      () => import('@/content/components/form/number-field/number-field-error.demo')
    ),
    file: 'content/components/form/number-field/number-field-error.demo.tsx',
  },
  'number-field-format': {
    name: 'number-field-format',
    demo: dynamic(
      () => import('@/content/components/form/number-field/number-field-format.demo')
    ),
    file: 'content/components/form/number-field/number-field-format.demo.tsx',
  },
  'number-field-hide': {
    name: 'number-field-hide',
    demo: dynamic(
      () => import('@/content/components/form/number-field/number-field-hide.demo')
    ),
    file: 'content/components/form/number-field/number-field-hide.demo.tsx',
  },
  'number-field-required': {
    name: 'number-field-required',
    demo: dynamic(
      () => import('@/content/components/form/number-field/number-field-required.demo')
    ),
    file: 'content/components/form/number-field/number-field-required.demo.tsx',
  },
  'number-field-simple': {
    name: 'number-field-simple',
    demo: dynamic(
      () => import('@/content/components/form/number-field/number-field-simple.demo')
    ),
    file: 'content/components/form/number-field/number-field-simple.demo.tsx',
  },
  'number-field-values': {
    name: 'number-field-values',
    demo: dynamic(
      () => import('@/content/components/form/number-field/number-field-values.demo')
    ),
    file: 'content/components/form/number-field/number-field-values.demo.tsx',
  },
  'radio-disabled': {
    name: 'radio-disabled',
    demo: dynamic(
      () => import('@/content/components/form/radio/radio-disabled.demo')
    ),
    file: 'content/components/form/radio/radio-disabled.demo.tsx',
  },
  'radio-error': {
    name: 'radio-error',
    demo: dynamic(
      () => import('@/content/components/form/radio/radio-error.demo')
    ),
    file: 'content/components/form/radio/radio-error.demo.tsx',
  },
  'radio-required': {
    name: 'radio-required',
    demo: dynamic(
      () => import('@/content/components/form/radio/radio-required.demo')
    ),
    file: 'content/components/form/radio/radio-required.demo.tsx',
  },
  'radio': {
    name: 'radio',
    demo: dynamic(
      () => import('@/content/components/form/radio/radio.demo')
    ),
    file: 'content/components/form/radio/radio.demo.tsx',
  },
  'search-field-basic': {
    name: 'search-field-basic',
    demo: dynamic(
      () => import('@/content/components/form/search-field/search-field-basic.demo')
    ),
    file: 'content/components/form/search-field/search-field-basic.demo.tsx',
  },
  'search-field-disabled': {
    name: 'search-field-disabled',
    demo: dynamic(
      () => import('@/content/components/form/search-field/search-field-disabled.demo')
    ),
    file: 'content/components/form/search-field/search-field-disabled.demo.tsx',
  },
  'search-field-error': {
    name: 'search-field-error',
    demo: dynamic(
      () => import('@/content/components/form/search-field/search-field-error.demo')
    ),
    file: 'content/components/form/search-field/search-field-error.demo.tsx',
  },
  'search-field-readoOnly': {
    name: 'search-field-readoOnly',
    demo: dynamic(
      () => import('@/content/components/form/search-field/search-field-readoOnly.demo')
    ),
    file: 'content/components/form/search-field/search-field-readoOnly.demo.tsx',
  },
  'search-field-req': {
    name: 'search-field-req',
    demo: dynamic(
      () => import('@/content/components/form/search-field/search-field-req.demo')
    ),
    file: 'content/components/form/search-field/search-field-req.demo.tsx',
  },
  'field-group-basic': {
    name: 'field-group-basic',
    demo: dynamic(
      () => import('@/content/components/form/fieldgroup/field-group-basic.demo')
    ),
    file: 'content/components/form/fieldgroup/field-group-basic.demo.tsx',
  },
  'select-basic': {
    name: 'select-basic',
    demo: dynamic(
      () => import('@/content/components/form/select/select-basic.demo')
    ),
    file: 'content/components/form/select/select-basic.demo.tsx',
  },
  'select-default-selected': {
    name: 'select-default-selected',
    demo: dynamic(
      () => import('@/content/components/form/select/select-default-selected.demo')
    ),
    file: 'content/components/form/select/select-default-selected.demo.tsx',
  },
  'select-disabled-keys': {
    name: 'select-disabled-keys',
    demo: dynamic(
      () => import('@/content/components/form/select/select-disabled-keys.demo')
    ),
    file: 'content/components/form/select/select-disabled-keys.demo.tsx',
  },
  'select-disabled': {
    name: 'select-disabled',
    demo: dynamic(
      () => import('@/content/components/form/select/select-disabled.demo')
    ),
    file: 'content/components/form/select/select-disabled.demo.tsx',
  },
  'select-section': {
    name: 'select-section',
    demo: dynamic(
      () => import('@/content/components/form/select/select-section.demo')
    ),
    file: 'content/components/form/select/select-section.demo.tsx',
  },
  'slider-controlled': {
    name: 'slider-controlled',
    demo: dynamic(
      () => import('@/content/components/form/slider/slider-controlled.demo')
    ),
    file: 'content/components/form/slider/slider-controlled.demo.tsx',
  },
  'slider-disabled': {
    name: 'slider-disabled',
    demo: dynamic(
      () => import('@/content/components/form/slider/slider-disabled.demo')
    ),
    file: 'content/components/form/slider/slider-disabled.demo.tsx',
  },
  'slider-format': {
    name: 'slider-format',
    demo: dynamic(
      () => import('@/content/components/form/slider/slider-format.demo')
    ),
    file: 'content/components/form/slider/slider-format.demo.tsx',
  },
  'slider-max': {
    name: 'slider-max',
    demo: dynamic(
      () => import('@/content/components/form/slider/slider-max.demo')
    ),
    file: 'content/components/form/slider/slider-max.demo.tsx',
  },
  'slider-steps': {
    name: 'slider-steps',
    demo: dynamic(
      () => import('@/content/components/form/slider/slider-steps.demo')
    ),
    file: 'content/components/form/slider/slider-steps.demo.tsx',
  },
  'slider-uncontrolled': {
    name: 'slider-uncontrolled',
    demo: dynamic(
      () => import('@/content/components/form/slider/slider-uncontrolled.demo')
    ),
    file: 'content/components/form/slider/slider-uncontrolled.demo.tsx',
  },
  'slider-width': {
    name: 'slider-width',
    demo: dynamic(
      () => import('@/content/components/form/slider/slider-width.demo')
    ),
    file: 'content/components/form/slider/slider-width.demo.tsx',
  },
  'basic-tag': {
    name: 'basic-tag',
    demo: dynamic(
      () => import('@/content/components/form/tag/basic-tag.demo')
    ),
    file: 'content/components/form/tag/basic-tag.demo.tsx',
  },
  'label-tag': {
    name: 'label-tag',
    demo: dynamic(
      () => import('@/content/components/form/tag/label-tag.demo')
    ),
    file: 'content/components/form/tag/label-tag.demo.tsx',
  },
  'remove-tag': {
    name: 'remove-tag',
    demo: dynamic(
      () => import('@/content/components/form/tag/remove-tag.demo')
    ),
    file: 'content/components/form/tag/remove-tag.demo.tsx',
  },
  'text-area-basic': {
    name: 'text-area-basic',
    demo: dynamic(
      () => import('@/content/components/form/text-area/text-area-basic.demo')
    ),
    file: 'content/components/form/text-area/text-area-basic.demo.tsx',
  },
  'text-area-disabled': {
    name: 'text-area-disabled',
    demo: dynamic(
      () => import('@/content/components/form/text-area/text-area-disabled.demo')
    ),
    file: 'content/components/form/text-area/text-area-disabled.demo.tsx',
  },
  'text-area-error': {
    name: 'text-area-error',
    demo: dynamic(
      () => import('@/content/components/form/text-area/text-area-error.demo')
    ),
    file: 'content/components/form/text-area/text-area-error.demo.tsx',
  },
  'text-area-req': {
    name: 'text-area-req',
    demo: dynamic(
      () => import('@/content/components/form/text-area/text-area-req.demo')
    ),
    file: 'content/components/form/text-area/text-area-req.demo.tsx',
  },
  'switch-active-disabled': {
    name: 'switch-active-disabled',
    demo: dynamic(
      () => import('@/content/components/form/switch/switch-active-disabled.demo')
    ),
    file: 'content/components/form/switch/switch-active-disabled.demo.tsx',
  },
  'switch-active': {
    name: 'switch-active',
    demo: dynamic(
      () => import('@/content/components/form/switch/switch-active.demo')
    ),
    file: 'content/components/form/switch/switch-active.demo.tsx',
  },
  'switch-basic': {
    name: 'switch-basic',
    demo: dynamic(
      () => import('@/content/components/form/switch/switch-basic.demo')
    ),
    file: 'content/components/form/switch/switch-basic.demo.tsx',
  },
  'switch-disabled': {
    name: 'switch-disabled',
    demo: dynamic(
      () => import('@/content/components/form/switch/switch-disabled.demo')
    ),
    file: 'content/components/form/switch/switch-disabled.demo.tsx',
  },
  'textfield-basic': {
    name: 'textfield-basic',
    demo: dynamic(
      () => import('@/content/components/form/textfield/textfield-basic.demo')
    ),
    file: 'content/components/form/textfield/textfield-basic.demo.tsx',
  },
  'textfield-disabled': {
    name: 'textfield-disabled',
    demo: dynamic(
      () => import('@/content/components/form/textfield/textfield-disabled.demo')
    ),
    file: 'content/components/form/textfield/textfield-disabled.demo.tsx',
  },
  'textfield-error': {
    name: 'textfield-error',
    demo: dynamic(
      () => import('@/content/components/form/textfield/textfield-error.demo')
    ),
    file: 'content/components/form/textfield/textfield-error.demo.tsx',
  },
  'textfield-group': {
    name: 'textfield-group',
    demo: dynamic(
      () => import('@/content/components/form/textfield/textfield-group.demo')
    ),
    file: 'content/components/form/textfield/textfield-group.demo.tsx',
  },
  'textfield-number': {
    name: 'textfield-number',
    demo: dynamic(
      () => import('@/content/components/form/textfield/textfield-number.demo')
    ),
    file: 'content/components/form/textfield/textfield-number.demo.tsx',
  },
  'textfield-req': {
    name: 'textfield-req',
    demo: dynamic(
      () => import('@/content/components/form/textfield/textfield-req.demo')
    ),
    file: 'content/components/form/textfield/textfield-req.demo.tsx',
  },
  'textfield-types': {
    name: 'textfield-types',
    demo: dynamic(
      () => import('@/content/components/form/textfield/textfield-types.demo')
    ),
    file: 'content/components/form/textfield/textfield-types.demo.tsx',
  },
  'rightside': {
    name: 'rightside',
    demo: dynamic(
      () => import('@/content/components/layout/aside/rightside.demo')
    ),
    file: 'content/components/layout/aside/rightside.demo.tsx',
  },
  'space': {
    name: 'space',
    demo: dynamic(
      () => import('@/content/components/layout/aside/space.demo')
    ),
    file: 'content/components/layout/aside/space.demo.tsx',
  },
  'horizontal-breakout': {
    name: 'horizontal-breakout',
    demo: dynamic(
      () => import('@/content/components/layout/breakout/horizontal-breakout.demo')
    ),
    file: 'content/components/layout/breakout/horizontal-breakout.demo.tsx',
  },
  'iframe-breakout': {
    name: 'iframe-breakout',
    demo: dynamic(
      () => import('@/content/components/layout/breakout/iframe-breakout.demo')
    ),
    file: 'content/components/layout/breakout/iframe-breakout.demo.tsx',
  },
  'vertical-breakout': {
    name: 'vertical-breakout',
    demo: dynamic(
      () => import('@/content/components/layout/breakout/vertical-breakout.demo')
    ),
    file: 'content/components/layout/breakout/vertical-breakout.demo.tsx',
  },
  'golden-aspect': {
    name: 'golden-aspect',
    demo: dynamic(
      () => import('@/content/components/layout/aspect/golden-aspect.demo')
    ),
    file: 'content/components/layout/aspect/golden-aspect.demo.tsx',
  },
  'map': {
    name: 'map',
    demo: dynamic(
      () => import('@/content/components/layout/aspect/map.demo')
    ),
    file: 'content/components/layout/aspect/map.demo.tsx',
  },
  'ratio-square': {
    name: 'ratio-square',
    demo: dynamic(
      () => import('@/content/components/layout/aspect/ratio-square.demo')
    ),
    file: 'content/components/layout/aspect/ratio-square.demo.tsx',
  },
  'video': {
    name: 'video',
    demo: dynamic(
      () => import('@/content/components/layout/aspect/video.demo')
    ),
    file: 'content/components/layout/aspect/video.demo.tsx',
  },
  'space-center': {
    name: 'space-center',
    demo: dynamic(
      () => import('@/content/components/layout/center/space-center.demo')
    ),
    file: 'content/components/layout/center/space-center.demo.tsx',
  },
  'text-center': {
    name: 'text-center',
    demo: dynamic(
      () => import('@/content/components/layout/center/text-center.demo')
    ),
    file: 'content/components/layout/center/text-center.demo.tsx',
  },
  'width-center': {
    name: 'width-center',
    demo: dynamic(
      () => import('@/content/components/layout/center/width-center.demo')
    ),
    file: 'content/components/layout/center/width-center.demo.tsx',
  },
  'collapse-columns': {
    name: 'collapse-columns',
    demo: dynamic(
      () => import('@/content/components/layout/columns/collapse-columns.demo')
    ),
    file: 'content/components/layout/columns/collapse-columns.demo.tsx',
  },
  'layout-columns': {
    name: 'layout-columns',
    demo: dynamic(
      () => import('@/content/components/layout/columns/layout-columns.demo')
    ),
    file: 'content/components/layout/columns/layout-columns.demo.tsx',
  },
  'space-columns': {
    name: 'space-columns',
    demo: dynamic(
      () => import('@/content/components/layout/columns/space-columns.demo')
    ),
    file: 'content/components/layout/columns/space-columns.demo.tsx',
  },
  'stretch-columns-switch': {
    name: 'stretch-columns-switch',
    demo: dynamic(
      () => import('@/content/components/layout/columns/stretch-columns-switch.demo')
    ),
    file: 'content/components/layout/columns/stretch-columns-switch.demo.tsx',
  },
  'stretch-columns': {
    name: 'stretch-columns',
    demo: dynamic(
      () => import('@/content/components/layout/columns/stretch-columns.demo')
    ),
    file: 'content/components/layout/columns/stretch-columns.demo.tsx',
  },
  'full-container': {
    name: 'full-container',
    demo: dynamic(
      () => import('@/content/components/layout/container/full-container.demo')
    ),
    file: 'content/components/layout/container/full-container.demo.tsx',
  },
  'small-container': {
    name: 'small-container',
    demo: dynamic(
      () => import('@/content/components/layout/container/small-container.demo')
    ),
    file: 'content/components/layout/container/small-container.demo.tsx',
  },
  'inline-alignments': {
    name: 'inline-alignments',
    demo: dynamic(
      () => import('@/content/components/layout/inline/inline-alignments.demo')
    ),
    file: 'content/components/layout/inline/inline-alignments.demo.tsx',
  },
  'inline-elements': {
    name: 'inline-elements',
    demo: dynamic(
      () => import('@/content/components/layout/inline/inline-elements.demo')
    ),
    file: 'content/components/layout/inline/inline-elements.demo.tsx',
  },
  'inline-nested': {
    name: 'inline-nested',
    demo: dynamic(
      () => import('@/content/components/layout/inline/inline-nested.demo')
    ),
    file: 'content/components/layout/inline/inline-nested.demo.tsx',
  },
  'inline-spacing': {
    name: 'inline-spacing',
    demo: dynamic(
      () => import('@/content/components/layout/inline/inline-spacing.demo')
    ),
    file: 'content/components/layout/inline/inline-spacing.demo.tsx',
  },
  'inset-equal': {
    name: 'inset-equal',
    demo: dynamic(
      () => import('@/content/components/layout/inset/inset-equal.demo')
    ),
    file: 'content/components/layout/inset/inset-equal.demo.tsx',
  },
  'inset-hv': {
    name: 'inset-hv',
    demo: dynamic(
      () => import('@/content/components/layout/inset/inset-hv.demo')
    ),
    file: 'content/components/layout/inset/inset-hv.demo.tsx',
  },
  'split-inline': {
    name: 'split-inline',
    demo: dynamic(
      () => import('@/content/components/layout/split/split-inline.demo')
    ),
    file: 'content/components/layout/split/split-inline.demo.tsx',
  },
  'split-stack': {
    name: 'split-stack',
    demo: dynamic(
      () => import('@/content/components/layout/split/split-stack.demo')
    ),
    file: 'content/components/layout/split/split-stack.demo.tsx',
  },
  'tiles-autoRows': {
    name: 'tiles-autoRows',
    demo: dynamic(
      () => import('@/content/components/layout/tiles/tiles-autoRows.demo')
    ),
    file: 'content/components/layout/tiles/tiles-autoRows.demo.tsx',
  },
  'tiles-complex': {
    name: 'tiles-complex',
    demo: dynamic(
      () => import('@/content/components/layout/tiles/tiles-complex.demo')
    ),
    file: 'content/components/layout/tiles/tiles-complex.demo.tsx',
  },
  'tiles-itemwidth': {
    name: 'tiles-itemwidth',
    demo: dynamic(
      () => import('@/content/components/layout/tiles/tiles-itemwidth.demo')
    ),
    file: 'content/components/layout/tiles/tiles-itemwidth.demo.tsx',
  },
  'tiles-spacing': {
    name: 'tiles-spacing',
    demo: dynamic(
      () => import('@/content/components/layout/tiles/tiles-spacing.demo')
    ),
    file: 'content/components/layout/tiles/tiles-spacing.demo.tsx',
  },
  'tiles-stretch': {
    name: 'tiles-stretch',
    demo: dynamic(
      () => import('@/content/components/layout/tiles/tiles-stretch.demo')
    ),
    file: 'content/components/layout/tiles/tiles-stretch.demo.tsx',
  },
  'tabs-disabled': {
    name: 'tabs-disabled',
    demo: dynamic(
      () => import('@/content/components/navigation/tabs/tabs-disabled.demo')
    ),
    file: 'content/components/navigation/tabs/tabs-disabled.demo.tsx',
  },
  'tabs-large': {
    name: 'tabs-large',
    demo: dynamic(
      () => import('@/content/components/navigation/tabs/tabs-large.demo')
    ),
    file: 'content/components/navigation/tabs/tabs-large.demo.tsx',
  },
  'tabs-selectedKey': {
    name: 'tabs-selectedKey',
    demo: dynamic(
      () => import('@/content/components/navigation/tabs/tabs-selectedKey.demo')
    ),
    file: 'content/components/navigation/tabs/tabs-selectedKey.demo.tsx',
  },
  'stack-horizontal': {
    name: 'stack-horizontal',
    demo: dynamic(
      () => import('@/content/components/layout/stack/stack-horizontal.demo')
    ),
    file: 'content/components/layout/stack/stack-horizontal.demo.tsx',
  },
  'stack-nested': {
    name: 'stack-nested',
    demo: dynamic(
      () => import('@/content/components/layout/stack/stack-nested.demo')
    ),
    file: 'content/components/layout/stack/stack-nested.demo.tsx',
  },
  'stack-spacing': {
    name: 'stack-spacing',
    demo: dynamic(
      () => import('@/content/components/layout/stack/stack-spacing.demo')
    ),
    file: 'content/components/layout/stack/stack-spacing.demo.tsx',
  },
  'stack-vertical': {
    name: 'stack-vertical',
    demo: dynamic(
      () => import('@/content/components/layout/stack/stack-vertical.demo')
    ),
    file: 'content/components/layout/stack/stack-vertical.demo.tsx',
  },
  'kebab-menu': {
    name: 'kebab-menu',
    demo: dynamic(
      () => import('@/content/components/overlay/menu/kebab-menu.demo')
    ),
    file: 'content/components/overlay/menu/kebab-menu.demo.tsx',
  },
  'menu-action': {
    name: 'menu-action',
    demo: dynamic(
      () => import('@/content/components/overlay/menu/menu-action.demo')
    ),
    file: 'content/components/overlay/menu/menu-action.demo.tsx',
  },
  'menu-disabled': {
    name: 'menu-disabled',
    demo: dynamic(
      () => import('@/content/components/overlay/menu/menu-disabled.demo')
    ),
    file: 'content/components/overlay/menu/menu-disabled.demo.tsx',
  },
  'menu-open-dialog': {
    name: 'menu-open-dialog',
    demo: dynamic(
      () => import('@/content/components/overlay/menu/menu-open-dialog.demo')
    ),
    file: 'content/components/overlay/menu/menu-open-dialog.demo.tsx',
  },
  'menu-open': {
    name: 'menu-open',
    demo: dynamic(
      () => import('@/content/components/overlay/menu/menu-open.demo')
    ),
    file: 'content/components/overlay/menu/menu-open.demo.tsx',
  },
  'menu-section': {
    name: 'menu-section',
    demo: dynamic(
      () => import('@/content/components/overlay/menu/menu-section.demo')
    ),
    file: 'content/components/overlay/menu/menu-section.demo.tsx',
  },
  'dialog-dismiss': {
    name: 'dialog-dismiss',
    demo: dynamic(
      () => import('@/content/components/overlay/dialog/dialog-dismiss.demo')
    ),
    file: 'content/components/overlay/dialog/dialog-dismiss.demo.tsx',
  },
  'dialog-form': {
    name: 'dialog-form',
    demo: dynamic(
      () => import('@/content/components/overlay/dialog/dialog-form.demo')
    ),
    file: 'content/components/overlay/dialog/dialog-form.demo.tsx',
  },
  'menu-open-dialog': {
    name: 'menu-open-dialog',
    demo: dynamic(
      () => import('@/content/components/overlay/dialog/menu-open-dialog.demo')
    ),
    file: 'content/components/overlay/dialog/menu-open-dialog.demo.tsx',
  },
  'tooltip-basic': {
    name: 'tooltip-basic',
    demo: dynamic(
      () => import('@/content/components/overlay/tooltip/tooltip-basic.demo')
    ),
    file: 'content/components/overlay/tooltip/tooltip-basic.demo.tsx',
  },
  'tooltip-custom': {
    name: 'tooltip-custom',
    demo: dynamic(
      () => import('@/content/components/overlay/tooltip/tooltip-custom.demo')
    ),
    file: 'content/components/overlay/tooltip/tooltip-custom.demo.tsx',
  },
  'tooltip-focus': {
    name: 'tooltip-focus',
    demo: dynamic(
      () => import('@/content/components/overlay/tooltip/tooltip-focus.demo')
    ),
    file: 'content/components/overlay/tooltip/tooltip-focus.demo.tsx',
  },
  'tooltip-pressed': {
    name: 'tooltip-pressed',
    demo: dynamic(
      () => import('@/content/components/overlay/tooltip/tooltip-pressed.demo')
    ),
    file: 'content/components/overlay/tooltip/tooltip-pressed.demo.tsx',
  },
} as const;